### ISSUE TITLE
The ShadowRenderer its not working

### ISSUE THREAD

**Issue by Mankimann** [Saar25/Lwjgl#2]
i use the intellij IDE,  because kotlin not works so good on eclipse.

The shader renderer are written in kotlin and i learning kotlin and scala still first.

this is the Exception

```
Exception in thread "main" java.lang.ExceptionInInitializerError
	at engine.rendering.RenderManager.<init>(RenderManager.java:61)
	at engine.gameengine.GameEngine.init(GameEngine.java:35)
	at game.showcase.CubeGameShowcase.main(CubeGameShowcase.java:40)
Caused by: opengl.shaders.ShaderCompileException: Shader type: FRAGMENT, Error compiling Shader code:
Fragment shader failed to compile with the following errors:
ERROR: 0:11: error(#202) No matching overloaded function found: texture
ERROR: 0:11: error(#216) Vector field selection out of range "a"
ERROR: error(#273) 2 compilation errors.  No code generated


	at opengl.shaders.Shader.init(Shader.java:97)
	at opengl.shaders.ShadersProgram.<init>(ShadersProgram.java:24)
	at opengl.shaders.ShadersProgram.create(ShadersProgram.java:37)
	at opengl.shaders.ShadersProgram.create(ShadersProgram.java:43)
	at engine.shadows.ShadowsRenderer.<init>(ShadowsRenderer.kt:12)
	at engine.shadows.ShadowsRenderer.<clinit>(ShadowsRenderer.kt:93)
	... 3 more

Process finished with exit code 1
```

**Comment by Saar25** [comment]
Hi
Which opengl version have you got on your computer?

**Comment by Mankimann** [comment]
Hi,
i use opengl version 4,6

**Comment by Saar25** [comment]
Try opening the shader resources/engine/shadows/shadowsFrag.glsl
and replace
`texture(texture, texCoord).a`
with
`texture2D(texture, texCoord).a`

**Comment by Mankimann** [comment]
ok, its not working

the new Exception ^^:

```
Exception in thread "main" java.lang.ExceptionInInitializerError
	at engine.rendering.RenderManager.<init>(RenderManager.java:62)
	at engine.gameengine.GameEngine.init(GameEngine.java:35)
	at game.showcase.CubeGameShowcase.main(CubeGameShowcase.java:40)
Caused by: opengl.shaders.ShaderCompileException: Shader type: FRAGMENT, Error compiling Shader code:
Fragment shader failed to compile with the following errors:
ERROR: 0:180: error(#202) No matching overloaded function found: texture
ERROR: 0:180: error(#160) Cannot convert from: "const float" to: "highp 4-component vector of vec4"
ERROR: error(#273) 2 compilation errors.  No code generated


	at opengl.shaders.Shader.init(Shader.java:97)
	at opengl.shaders.ShadersProgram.<init>(ShadersProgram.java:24)
	at opengl.shaders.ShadersProgram.create(ShadersProgram.java:37)
	at tegui.render.GuiRenderer.<init>(GuiRenderer.kt:20)
	at tegui.render.GuiRenderer.<clinit>(GuiRenderer.kt:104)
	... 3 more

Process finished with exit code 1
```

**Comment by Saar25** [comment]
Ok I believe the texture() method was the problem
I added a simple check in every shader that was using the texture method
`
#if __VERSION__ < 130
#define sTexture texture2D
#else
#define sTexture texture
#endif
`
I've updated the master, try running the code again please

**Comment by Mankimann** [comment]
ok i have running the new code,

here is the new Exception:
```
Exception in thread "main" java.lang.ExceptionInInitializerError
	at engine.rendering.RenderManager.<init>(RenderManager.java:61)
	at engine.gameengine.GameEngine.init(GameEngine.java:35)
	at game.showcase.CubeGameShowcase.main(CubeGameShowcase.java:40)
Caused by: opengl.shaders.ShaderCompileException: Shader type: FRAGMENT, Error compiling Shader code:
Fragment shader failed to compile with the following errors:
ERROR: 0:17: error(#202) No matching overloaded function found: texture
ERROR: 0:17: error(#216) Vector field selection out of range "a"
ERROR: error(#273) 2 compilation errors.  No code generated


	at opengl.shaders.Shader.init(Shader.java:97)
	at opengl.shaders.ShadersProgram.<init>(ShadersProgram.java:24)
	at opengl.shaders.ShadersProgram.create(ShadersProgram.java:37)
	at opengl.shaders.ShadersProgram.create(ShadersProgram.java:43)
	at engine.shadows.ShadowsRenderer.<init>(ShadowsRenderer.kt:15)
	at engine.shadows.ShadowsRenderer.<clinit>(ShadowsRenderer.kt:94)
	... 3 more
```

**Comment by Saar25** [comment]
Indeed strage
It seems to me that your opengl version is high enough and yet cannot use texture() method
I would suggest you to replace texture() ( and sTexture() ) with texture2D() manually for now

**Comment by Mankimann** [comment]
Thank you, but the method texture() and sTexture() to replace with texture2d its not works.
yes i think the opengl version is high enough.
i use the jdk version 1.8 and the pom.xml from the master repository
![amd](https://user-images.githubusercontent.com/23460028/104754149-2e92a380-5759-11eb-8b86-f2e6e0c26a33.png)

**Comment by Saar25** [comment]
The same exception occurs?

**Comment by Mankimann** [comment]
the Exception

```
Exception in thread "main" java.lang.ExceptionInInitializerError
	at engine.rendering.RenderManager.<init>(RenderManager.java:61)
	at engine.gameengine.GameEngine.init(GameEngine.java:35)
	at game.showcase.CubeGameShowcase.main(CubeGameShowcase.java:40)
Caused by: opengl.shaders.ShaderCompileException: Shader type: FRAGMENT, Error compiling Shader code:
Fragment shader failed to compile with the following errors:
ERROR: 0:17: error(#202) No matching overloaded function found: texture2D
ERROR: 0:17: error(#216) Vector field selection out of range "a"
ERROR: error(#273) 2 compilation errors.  No code generated


	at opengl.shaders.Shader.init(Shader.java:97)
	at opengl.shaders.ShadersProgram.<init>(ShadersProgram.java:24)
	at opengl.shaders.ShadersProgram.create(ShadersProgram.java:37)
	at opengl.shaders.ShadersProgram.create(ShadersProgram.java:43)
	at engine.shadows.ShadowsRenderer.<init>(ShadowsRenderer.kt:15)
	at engine.shadows.ShadowsRenderer.<clinit>(ShadowsRenderer.kt:94)
	... 3 more

Process finished with exit code 1
 
```

The code:

```
#version 400 core

#if __VERSION__ < 130
#define sTexture texture2D
#else
#define sTexture texture
#endif

in vec2 texCoord;

out float fragDepth;

uniform sampler2D texture;

void main() {

    if (texture2D(texture2D, texCoord).a < .1) {
        discard;
    }

    fragDepth = gl_FragCoord.z;
}

```

**Comment by Skydeke** [comment]
I had the same problem... For me the line uniform sampler2D texture; was the problem, because the compiler got confused with the attribute texture and the GLSL method texture() naming the sampler2D  a different variablename fixed it for me, (Also think of chanhing it in the java code to bind the attributes correctly)

**Comment by Skydeke** [comment]
While I'm at it... You will propably also have a problem with Objects not being rendered correctly. This is because the Index-Count given as parameter for GlDrawArray and other draw methods isn't correct. It is just the num ber in bytes but forgets the data type the vao stores. (This comment is from memory, I'd need to look at the changes I made to it to tell you exactly what was wrong.)

**Comment by Saar25** [comment]
> I had the same problem... For me the line uniform sampler2D texture; was the problem, because the compiler got confused with the attribute texture and the GLSL method texture() naming the sampler2D a different variablename fixed it for me, (Also think of chanhing it in the java code to bind the attributes correctly)

Thank you for pointing that out
I have never had a problem with name uniform name
and I didn't know the uniform name can be an issue
I've changed it in any case

**Comment by Mankimann** [comment]
no, thank you for your help 👍 
it works, this is a great engine :) 
But i have yet a problem with the full uniform light array's of colour and intensity.

```
Cannot locate uniform lights[0].colour
Cannot locate uniform lights[0].intensity
Cannot locate uniform lights[1].colour
Cannot locate uniform lights[1].intensity
Cannot locate uniform lights[2].colour
Cannot locate uniform lights[2].intensity
Cannot locate uniform lights[3].colour
Cannot locate uniform lights[3].intensity
Cannot locate uniform lights[4].colour
Cannot locate uniform lights[4].intensity
Cannot locate uniform lights[5].colour
Cannot locate uniform lights[5].intensity
Cannot locate uniform lights[6].colour
Cannot locate uniform lights[6].intensity
Cannot locate uniform lights[7].colour
Cannot locate uniform lights[7].intensity
Cannot locate uniform lights[8].colour
Cannot locate uniform lights[8].intensity
Cannot locate uniform lights[9].colour
Cannot locate uniform lights[9].intensity
Cannot locate uniform lights[0].intensity
Cannot locate uniform lights[1].intensity
Cannot locate uniform lights[2].intensity
Cannot locate uniform lights[3].intensity
Cannot locate uniform lights[4].intensity
Cannot locate uniform lights[5].intensity
Cannot locate uniform lights[6].intensity
Cannot locate uniform lights[7].intensity
Cannot locate uniform lights[8].intensity
Cannot locate uniform lights[9].intensity

```

**Comment by Saar25** [comment]
These are just warnings, as long as they do now affect the rendering I suggest you to ignore them
